apiVersion: v1
stringData:
  POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
  DATABASE_URL: postgresql://{{ copier__project_slug }}:__POSTGRES_PASSWORD__@postgres/{{ copier__project_slug }}
  DJANGO_SECRET_KEY: __DJANGO_SECRET_KEY__
kind: Secret
metadata:
  name: secrets-config
type: Opaque
