---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-sandbox-{{ copier__project_slug }}-tls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: argocd-sandbox-{{ copier__project_slug }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - argocd.sandbox.{{ copier__domain_name }}
